---
# tasks file for ntp
- name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
  ansible.builtin.include_vars:
    file: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family | replace(' ', '_') ~ '.yml' }}"
        - default.yml
      paths:
        - vars

- name: Install NTP on RedHat
  ansible.builtin.yum:
    name:
      - ntp
  async: 3600
  poll: 10
  when: ansible_pkg_mgr == 'yum'

- name: Install NTP on Fedora
  ansible.builtin.dnf:
    name:
      - ntp
  async: 3600
  poll: 10
  when: ansible_pkg_mgr == 'dnf'

- name: Install NTP on Debian
  ansible.builtin.apt:
    name:
      - ntp
    update_cache: yes
  async: 3600
  poll: 10
  when: ansible_pkg_mgr == 'apt'

- name: Upload ntp configuration file
  ansible.builtin.template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify:
    - restart ntp